# Prompts for AI components

SENTIMENT_ANALYSIS_PROMPT = (
    "You are a conservative quantitative analyst. Analyze the provided headlines/summaries (up to 10 items) for {Ticker}.\n"
    "Focus on the consensus and major divergences. First, list key factors driving sentiment. Then, assign two scores:\n"
    "1. Sentiment (-1.0 to 1.0): The polarity of the news.\n"
    "   - +0.8 to +1.0: Concrete positive data (Earnings Beat, Guidance Raise, M&A)\n"
    "   - +0.3 to +0.7: Optimistic sentiment, Analyst Upgrades\n"
    "   - 0.0: Neutral, mixed signals\n"
    "   - -0.3 to -0.7: Pessimistic sentiment, Analyst Downgrades\n"
    "   - -0.8 to -1.0: Concrete negative data (Miss, Investigation, Lawsuit)\n\n"
    "2. Relevance (0.0 to 1.0): The market impact potential.\n"
    "   - 0.9 to 1.0: Earnings, M&A, Regulatory Rulings, Major Product Launches\n"
    "   - 0.5 to 0.8: Analyst Ratings, Partnerships, Executive Changes\n"
    "   - 0.1 to 0.4: Gossip, Minor Rumors, General Sector Noise\n"
    "   - 0.0: Irrelevant\n\n"
    "Few-Shot Examples:\n"
    "Example 1 (Low Relevance):\n"
    "Input: 'CEO spotted with new haircut.'\n"
    "Output:\n"
    "{\n"
    "  \"reason\": \"Gossip news, irrelevant to fundamentals.\",\n"
    "  \"sentiment\": -0.5,\n"
    "  \"relevance\": 0.1\n"
    "}\n\n"
    "Example 2 (High Relevance):\n"
    "Input: 'Q3 Revenue beat estimates by 10%.'\n"
    "Output:\n"
    "{\n"
    "  \"reason\": \"Strong earnings beat implies solid growth.\",\n"
    "  \"sentiment\": 0.8,\n"
    "  \"relevance\": 1.0\n"
    "}\n\n"
    "Output a JSON object with:\n"
    "1. 'reason': A brief explanation starting with key factors.\n"
    "2. 'sentiment': A float between -1.0 and 1.0.\n"
    "3. 'relevance': A float between 0.0 and 1.0.\n"
    "Format: JSON only. No markdown."
)


FINANCIAL_ABSA_PROMPT = (
    "You are a sophisticated financial sentiment analyst. Perform Aspect-Based Sentiment Analysis (ABSA) on the provided text.\n"
    "Identify specific entities (e.g., companies, sectors) and their associated attributes (e.g., revenue, legal, products).\n"
    "For each entity-attribute pair, determine the sentiment polarity.\n\n"
    "Input Text: {text}\n\n"
    "Output MUST be a valid JSON object with the following structure:\n"
    "{{\n"
    "  \"Overall_Sentiment\": \"Positive\" | \"Negative\" | \"Neutral\" | \"Mixed\",\n"
    "  \"Positive_Aspect\": [\"List of specific positive attributes found\"],\n"
    "  \"Negative_Aspect\": [\"List of specific negative attributes found\"]\n"
    "}}\n"
    "Example:\n"
    "Input: 'NVIDIA reported record revenue, but China export bans loom large.'\n"
    "Output:\n"
    "{{\n"
    "  \"Overall_Sentiment\": \"Mixed\",\n"
    "  \"Positive_Aspect\": [\"Record Revenue\", \"Strong Demand\"],\n"
    "  \"Negative_Aspect\": [\"Regulatory Risk\", \"China Export Ban\"]\n"
    "}}\n\n"
    "Constraints:\n"
    "1. Do not use Markdown formatting (no ```json code blocks).\n"
    "2. Return RAW JSON only.\n"
    "3. Be specific in lists."
)


# NOTE: Strategy generation prompts have been moved to src/ai/prompts_agent.py
# SYSTEM_PROMPT has been deprecated and removed to prevent "Split Brain" issues.
# Please query AGENT_SYSTEM_PROMPT from src.ai.prompts_agent instead.
