from abc import ABC
from enum import Enum
from typing import Optional, Dict
from datetime import datetime
import queue

class EventType(Enum):
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"

class Event(ABC):
    """
    Base Event class for event-driven system.
    """
    @property
    def type(self) -> EventType:
        raise NotImplementedError

class MarketEvent(Event):
    """
    Triggered when new market data updates are available.
    """
    def __init__(self, timestamp: datetime):
        self.timestamp = timestamp
        
    @property
    def type(self) -> EventType:
        return EventType.MARKET

class SignalEvent(Event):
    """
    Generated by the Strategy, suggesting a trade.
    """
    def __init__(self, strategy_id: str, symbol: str, timestamp: datetime, 
                 signal_type: str, strength: float = 1.0, target_qty: Optional[float] = None):
        """
        Args:
            signal_type: 'LONG', 'SHORT', 'EXIT'
            strength: 0.0 to 1.0 (conviction)
            target_qty: Optional explicit quantity (if None, Portfolio determines)
        """
        self.strategy_id = strategy_id
        self.symbol = symbol
        self.timestamp = timestamp
        self.signal_type = signal_type
        self.strength = strength
        self.target_qty = target_qty

    @property
    def type(self) -> EventType:
        return EventType.SIGNAL

class OrderEvent(Event):
    """
    Generated by the Portfolio/Risk Manager to send to Execution.
    """
    def __init__(self, symbol: str, order_type: str, quantity: float, direction: str):
        """
        Args:
            type: 'MKT' or 'LMT'
            direction: 'BUY' or 'SELL'
        """
        self.symbol = symbol
        self.order_type = order_type # 'MKT', 'LMT'
        self.quantity = quantity
        self.direction = direction

    @property
    def type(self) -> EventType:
        return EventType.ORDER
    
    def print_order(self):
        print(f"Order: {self.direction} {self.quantity} {self.symbol} @ {self.order_type}")

class FillEvent(Event):
    """
    Generated by the Execution Handler when an order is filled.
    """
    def __init__(self, timestamp: datetime, symbol: str, exchange: str, quantity: float, 
                 direction: str, fill_cost: float, commission: float = 0.0):
        self.timestamp = timestamp
        self.symbol = symbol
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_cost = fill_cost # total value without commission
        self.commission = commission

    @property
    def type(self) -> EventType:
        return EventType.FILL

    def net_cost(self) -> float:
        if self.direction == 'BUY':
            return self.fill_cost + self.commission
        else:
            return self.fill_cost - self.commission
